spring.datasource.url=jdbc:mysql://localhost:3306/employee_leave_portal
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
jwt.secret=${JWT_SECRET:mySuperSecretKeyForDevelopmentOnlyChangeThisInProduction123456}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.data.redis.host=localhost
spring.data.redis.port=6379